name: Linux CI

# ...at least it's working.
# I do not want to mess with this EVER AGAIN.

on:
  schedule:
    - cron: "30 9 * * 1"
  #  push:
  #    branches: [ "!legacy-system" ]
  workflow_dispatch:
  workflow_call:
#  pull_request:
#    types: [ "closed" ]
#    branches: [ "main" ]

jobs:
  prep-cryptopp:
    name: Prepare CryptoPP
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        id: cryp-cache
        uses: actions/cache@v5
        with:
          path: cryptopp
          key: ${{ runner.os }}-cryp-cache
      - name: Fetch & build library
        if: steps.cryp-cache.outputs.cache-hit != 'true'
        run: |
          wget https://cryptopp.com/cryptopp890.zip
          unzip -q cryptopp890.zip -d cryptopp
          cd cryptopp
          sudo make

  ship-it-lite:
    name: Ship the library (LITE ver.)
    runs-on: ubuntu-latest
    needs: [prep-cryptopp]
    steps:
      - name: Cache
        id: cryp-cache
        uses: actions/cache/restore@v5
        with:
          path: cryptopp
          key: ${{ runner.os }}-cryp-cache
      - name: Install libraries
        run: cd cryptopp ; sudo make install ; sudo apt update ; sudo apt install libsdl2-dev libsdl2-net-dev libsdl2-2.0-0 libsdl2-net-2.0-0 libcurl4-openssl-dev ; cd ..
      - name: Install OpenGL
        run: sudo apt install libgl1-mesa-dev
      - uses: actions/checkout@v4
      - name: make ship-it
        run: make ship-it os=linux lite=1
      - uses: actions/upload-artifact@master
        with:
          name: linux-gcc
          path: output/linux-gcc.zip

  build-ctl-tests-debug:
    name: Build CTL Tests (DEBUG)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenGL
        run: sudo apt install libgl1-mesa-dev
      - name: make tests
        run: |
          cd tests/ctl
          make debug os=linux
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-ctl-debug
          path: tests/ctl/output/debug

  build-ctl-tests-release:
    name: Build CTL Tests (RELEASE)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenGL
        run: sudo apt install libgl1-mesa-dev
      - name: make tests
        run: |
          cd tests/ctl
          make release os=linux
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-ctl-release
          path: tests/ctl/output/release

  build-core-lib-debug:
    name: Build Makai (DEBUG)
    runs-on: ubuntu-latest
    needs: [prep-cryptopp]
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenGL
        run: sudo apt install libgl1-mesa-dev
      - name: make debug
        run: |
          make debug os=linux lite=1
      - uses: actions/upload-artifact@master
        with:
          name: lib-debug
          path: output

  build-core-lib-release:
    name: Build Makai (RELEASE)
    runs-on: ubuntu-latest
    needs: [prep-cryptopp]
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenGL
        run: sudo apt install libgl1-mesa-dev
      - name: make debug
        run: |
          make release os=linux lite=1
      - uses: actions/upload-artifact@master
        with:
          name: lib-release
          path: output

  build-tooling:
    name: Build Tooling
    runs-on: ubuntu-latest
    needs: [build-core-lib-debug, build-core-lib-release]
    #    needs: install-gcc
    steps:
      - name: Cache
        id: cryp-cache
        uses: actions/cache/restore@v5
        with:
          path: cryptopp
          key: ${{ runner.os }}-cryp-cache
      - name: Install libraries
        run: cd cryptopp ; sudo make install ; sudo apt update ; sudo apt install libsdl2-dev libsdl2-net-dev libsdl2-2.0-0 libsdl2-net-2.0-0 libcurl4-openssl-dev ; cd ..
      - name: Install OpenGL
        run: sudo apt install libgl1-mesa-dev
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: lib-debug
          path: output
      - uses: actions/download-artifact@master
        with:
          name: lib-release
          path: output
      - name: make tooling os=linux lite=1
        run: |
          make tooling os=linux lite=1
      - uses: actions/upload-artifact@master
        with:
          name: tooling
          path: output/bin

  build-lib-tests-debug:
    name: Build API Tests (DEBUG)
    runs-on: ubuntu-latest
    needs: [build-core-lib-debug]
    steps:
      - name: Cache
        id: cryp-cache
        uses: actions/cache/restore@v5
        with:
          path: cryptopp
          key: ${{ runner.os }}-cryp-cache
      - name: Install libraries
        run: cd cryptopp ; sudo make install ; sudo apt update ; sudo apt install libsdl2-dev libsdl2-net-dev libsdl2-2.0-0 libsdl2-net-2.0-0 libcurl4-openssl-dev ; cd ..
      - name: Install OpenGL
        run: sudo apt install libgl1-mesa-dev
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: lib-debug
          path: output
      - name: make tests
        run: |
          cd tests/makai
          make debug os=linux from-lite=1
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-api-debug
          path: tests/makai/output/debug

  build-lib-tests-release:
    name: Build API Tests (RELEASE)
    runs-on: ubuntu-latest
    needs: [build-core-lib-release]
    steps:
      - name: Cache
        id: cryp-cache
        uses: actions/cache/restore@v5
        with:
          path: cryptopp
          key: ${{ runner.os }}-cryp-cache
      - name: Install libraries
        run: cd cryptopp ; sudo make install ; sudo apt update ; sudo apt install libsdl2-dev libsdl2-net-dev libsdl2-2.0-0 libsdl2-net-2.0-0 libcurl4-openssl-dev ; cd ..
      - name: Install OpenGL
        run: sudo apt install libgl1-mesa-dev
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: lib-debug
          path: output
      - name: make tests
        run: |
          cd tests/makai
          make release os=linux from-lite=1
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-api-release
          path: tests/makai/output/release
