name: Windows CI

# ...at least it's working.
# I do not want to mess with this EVER AGAIN.

on:
  schedule:
    - cron: "30 9 * * 1"
  #  push:
  #    branches: [ "!legacy-system" ]
  workflow_dispatch:
  workflow_call:
#  pull_request:
#    types: [ "closed" ]
#    branches: [ "main" ]

jobs:
  # install-gcc:
  #   name: Install Latest GCC Via MSYS2
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Install MSYS2
  #     uses: msys2/setup-msys2@v2
  #     with:
  #       msystem: MINGW64
  #       update: true
  #       install: git mingw-w64-x86_64-toolchain
  #   - name: Verify GCC Installation
  #     run: |
  #       gcc --version
  #       g++ --version
  #       mingw32-make --version
  ship-it-lite:
    name: Ship the library (FULL ver.)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    #    needs: install-gcc
    steps:
      - uses: actions/checkout@v4
      # Hellspawn BEGIN
      - uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain
          cache: false
      # Hellspawn END
      - name: make ship-it
        run: |
          pacman -S mingw-w64-x86_64-7zip --noconfirm --needed
          mingw32-make ship-it gmake=mingw32-make os=win compiler=msys2-gcc
      - uses: actions/upload-artifact@master
        with:
          name: windows-builds
          path: output/win-*.zip

  build-ctl-tests-debug:
    name: Build CTL Tests (DEBUG)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    #    needs: install-gcc
    steps:
      - uses: actions/checkout@v4
      # Hellspawn BEGIN
      - uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain
          cache: false
      # Hellspawn END
      - name: make tests
        run: |
          cd tests/ctl
          mingw32-make debug gmake=mingw32-make os=win
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-ctl-debug
          path: tests/ctl/output/debug

  # run-ctl-tests-debug:
  #   name: Run CTL Tests (DEBUG)
  #   runs-on: windows-latest
  #   needs: [build-ctl-tests-debug]
  #   steps:
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: tests-ctl-debug
  #         path: tests
  #     - name: run tests
  #       run: |
  #         cd tests
  #         for /r "." %%a in (*.debug.exe) do start "" "%%~fa"
  #         cd ..

  build-ctl-tests-release:
    name: Build CTL Tests (RELEASE)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    #    needs: install-gcc
    steps:
      - uses: actions/checkout@v4
      # Hellspawn BEGIN
      - uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain
          cache: false
      # Hellspawn END
      - name: make tests
        run: |
          cd tests/ctl
          mingw32-make release gmake=mingw32-make os=win
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-ctl-release
          path: tests/ctl/output/release

  # run-ctl-tests-release:
  #   name: Run CTL Tests (REOELEASE)
  #   runs-on: windows-latest
  #   needs: [build-ctl-tests-release]
  #   steps:
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: tests-ctl-release
  #         path: tests
  #     - name: run tests
  #       run: |
  #         cd tests
  #         for /r "." %%a in (*.release.exe) do start "" "%%~fa"
  #         cd ..

  build-core-lib-debug:
    name: Build Makai (DEBUG)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    #    needs: install-gcc
    steps:
      - uses: actions/checkout@v4
      # Hellspawn BEGIN
      - uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain
          cache: false
      # Hellspawn END
      - name: make debug gmake=mingw32-make
        run: |
          mingw32-make debug gmake=mingw32-make os=win
      - uses: actions/upload-artifact@master
        with:
          name: lib-debug
          path: output

  build-core-lib-release:
    name: Build Makai (RELEASE)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    #    needs: install-gcc
    steps:
      - uses: actions/checkout@v4
      # Hellspawn BEGIN
      - uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain
          cache: false
      # Hellspawn END
      - name: make release
        run: |
          mingw32-make release gmake=mingw32-make os=win
      - uses: actions/upload-artifact@master
        with:
          name: lib-release
          path: output

  build-tooling:
    name: Build Tooling
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    needs: [build-core-lib-debug, build-core-lib-release]
    #    needs: install-gcc
    steps:
      - uses: actions/checkout@v4
      # Hellspawn BEGIN
      - uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain
          cache: false
      # Hellspawn END
      - uses: actions/download-artifact@master
        with:
          name: lib-debug
          path: output
      - uses: actions/download-artifact@master
        with:
          name: lib-release
          path: output
      - name: make tooling
        run: |
          mingw32-make tooling gmake=mingw32-make os=win
      - uses: actions/upload-artifact@master
        with:
          name: tooling
          path: output/bin

  build-lib-tests-debug:
    name: Build API Tests (DEBUG)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    needs: [build-core-lib-debug]
    steps:
      - uses: actions/checkout@v4
      # Hellspawn BEGIN
      - uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain
          cache: false
      # Hellspawn END
      - uses: actions/download-artifact@master
        with:
          name: lib-debug
          path: output
      - name: make tests
        run: |
          cd tests/makai
          mingw32-make debug gmake=mingw32-make os=win
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-api-debug
          path: tests/makai/output/debug

  build-lib-tests-release:
    name: Build API Tests (RELEASE)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    needs: [build-core-lib-release]
    steps:
      - uses: actions/checkout@v4
      # Hellspawn BEGIN
      - uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-toolchain
          cache: false
      # Hellspawn END
      - uses: actions/download-artifact@master
        with:
          name: lib-release
          path: output
      - name: make tests
        run: |
          cd tests/makai
          mingw32-make release gmake=mingw32-make os=win
          cd ../..
      - uses: actions/upload-artifact@master
        with:
          name: tests-api-release
          path: tests/makai/output/release
